#!/usr/local/cpanel/3rdparty/perl/514/bin/perl

use strict;
use warnings;

use Running::Commentary;
run_with -critical;

my $t = shift @ARGV;
die "Please give me the .t file you'd pass to t/testcore-c.t\n" if !defined $t || !-f $t;
my $fyi = 0;
$SIG{__DIE__} = sub { _fyi(); };

unlink 'a.c', 'a';
warn "a.c still exists!\n" if -e "a.c";
warn "a still exists!\n" if -e "a";

run 'Building .c' => sub {
    run 'building' => "/usr/local/cpanel/3rdparty/perl/514/bin/perl -Iblib/arch -Iblib/lib -MO=-qq,C,-O2,-fno-warnings,-fno-fold,-oa.c $t";
    run 'checking' => sub {
        die ".c does not exist\n" if !-f "a.c";
        die ".c is empty\n" if -z _;
    };
};

run 'Compiling .c' => sub {
    run 'compiling' => '/usr/local/cpanel/3rdparty/perl/514/bin/perl -Iblib/arch -Iblib/lib script/cc_harness a.c -o a';
    run 'checking'  => sub {
        die "binary does not exist\n"    if !-f "a";
        die "binary is empty\n"          if -z _;
        die "binary is not executable\n" if !-x _;
    };
};

run 'Running binary' => './a';

_fyi();    # We call it here since nothing died and we want the info in case of test failure (which does not result in the binary exiuting uncleanly).

sub _fyi {
    print "\n\n[These might help]\n    perl -MO=Concise $t\n    perlcc -v5 -r $t\n--\n" unless $fyi++;
}
