TAINT_FAILURES = op/taint.bin

FAILURES = op/bop.bin op/override.bin op/reset.bin io/perlio.bin op/magic-27839.bin

TAINT_OK = op/utftaint.bin comp/opsubs.bin

TESTS_OK = base/cond.bin \
	base/if.bin \
	base/lex.bin \
	base/num.bin \
	base/pat.bin \
	base/rs.bin \
	base/term.bin \
	base/while.bin \
	cmd/elsif.bin \
	cmd/for.bin \
	cmd/mod.bin \
	cmd/subval.bin \
	cmd/switch.bin \
	cmd/while.bin \
	comp/bproto.bin \
	comp/cmdopt.bin \
	comp/colon.bin \
	comp/decl.bin \
	comp/fold.bin \
	comp/form_scope.bin \
	comp/line_debug.bin \
	comp/multiline.bin \
	comp/our.bin \
	comp/package_block.bin \
	comp/package.bin \
	comp/parser.bin \
	comp/proto.bin \
	comp/redef.bin \
	comp/require.bin \
	comp/retainedlines.bin \
	comp/term.bin \
	comp/uproto.bin \
	comp/use.bin \
	comp/utf.bin \
	io/argv.bin \
	io/binmode.bin \
	io/bom.bin \
	io/crlf.bin \
	io/crlf_through.bin \
	io/data.bin \
	io/defout.bin \
	io/dup.bin \
	io/eintr.bin \
	io/errnosig.bin \
	io/errno.bin \
	io/fflush.bin \
	io/fs.bin \
	io/inplace.bin \
	io/iofile.bin \
	io/iprefix.bin \
	io/layers.bin \
	io/nargv.bin \
	io/openpid.bin \
	io/open.bin \
	io/perlio_fail.bin \
	io/perlio_leaks.bin \
	io/perlio_open.bin \
	io/pipe.bin \
	io/print.bin \
	io/pvbm.bin \
	io/read.bin \
	io/say.bin \
	io/tell.bin \
	io/through.bin \
	io/utf8.bin \
	op/64bitint.bin \
	op/alarm.bin \
	op/anonsub.bin \
	op/append.bin \
	op/args.bin \
	op/arith.bin \
	op/array_base.bin \
	op/array.bin \
	op/assignwarn.bin \
	op/attrhand.bin \
	op/attrs.bin \
	op/auto.bin \
	op/avhv.bin \
	op/bless.bin \
	op/blocks.bin \
	op/caller.bin \
	op/chars.bin \
	op/chdir.bin \
	op/chop.bin \
	op/chr.bin \
	op/closure.bin \
	op/cmp.bin \
	op/concat2.bin \
	op/concat.bin \
	op/cond.bin \
	op/context.bin \
	op/cproto.bin \
	op/crypt.bin \
	op/dbm.bin \
	op/defins.bin \
	op/delete.bin \
	op/die_except.bin \
	op/die_exit.bin \
	op/die_keeperr.bin \
	op/die.bin \
	op/die_unwind.bin \
	op/dor.bin \
	op/do.bin \
	op/each_array.bin \
	op/each.bin \
	op/eval.bin \
	op/exec.bin \
	op/exists_sub.bin \
	op/exp.bin \
	op/fh.bin \
	op/filehandle.bin \
	op/filetest_stack_ok.bin \
	op/filetest.bin \
	op/filetest_t.bin \
	op/flip.bin \
	op/fork.bin \
	op/getpid.bin \
	op/getppid.bin \
	op/gmagic.bin \
	op/goto.bin \
	op/grent.bin \
	op/grep.bin \
	op/groups.bin \
	op/gv.bin \
	op/hashassign.bin \
	op/hash.bin \
	op/hashwarn.bin \
	op/inccode.bin \
	op/inccode-tie.bin \
	op/incfilter.bin \
	op/inc.bin \
	op/index.bin \
	op/index_thr.bin \
	op/int.bin \
	op/join.bin \
	op/kill0.bin \
	op/lc.bin \
	op/lc_user.bin \
	op/leaky-magic.bin \
	op/length.bin \
	op/lex_assign.bin \
	op/lex.bin \
	op/lfs.bin \
	op/list.bin \
	op/localref.bin \
	op/local.bin \
	op/loopctl.bin \
	op/lop.bin \
	op/magic_phase.bin \
	op/magic.bin \
	op/method.bin \
	op/mkdir.bin \
	op/mydef.bin \
	op/my_stash.bin \
	op/my.bin \
	op/negate.bin \
	op/not.bin \
	op/numconvert.bin \
	op/oct.bin \
	op/ord.bin \
	op/or.bin \
	op/overload_integer.bin \
	op/packagev.bin \
	op/pack.bin \
	op/pos.bin \
	op/pow.bin \
	op/print.bin \
	op/protowarn.bin \
	op/push.bin \
	op/pwent.bin \
	op/qq.bin \
	op/qr.bin \
	op/quotemeta.bin \
	op/rand.bin \
	op/range.bin \
	op/readdir.bin \
	op/readline.bin \
	op/read.bin \
	op/recurse.bin \
	op/ref.bin \
	op/repeat.bin \
	op/require_errors.bin \
	op/reverse.bin \
	op/runlevel.bin \
	op/setpgrpstack.bin \
	op/sigdispatch.bin \
	op/sleep.bin \
	op/smartkve.bin \
	op/smartmatch.bin \
	op/sort.bin \
	op/splice.bin \
	op/split.bin \
	op/split_unicode.bin \
	op/sprintf2.bin \
	op/sprintf.bin \
	op/srand.bin \
	op/sselect.bin \
	op/stash.bin \
	op/state.bin \
	op/stat.bin \
	op/study.bin \
	op/studytied.bin \
	op/sub_lval.bin \
	op/sub.bin \
	op/svleak.bin \
	op/switch.bin \
	op/symbolcache.bin \
	op/sysio.bin \
	op/tiearray.bin \
	op/tie_fetch_count.bin \
	op/tiehandle.bin \
	op/tie.bin \
	op/time_loop.bin \
	op/time.bin \
	op/tr.bin \
	op/turkish.bin \
	op/undef.bin \
	op/universal.bin \
	op/unshift.bin \
	op/upgrade.bin \
	op/utf8cache.bin \
	op/utf8decode.bin \
	op/utf8magic.bin \
	op/utfhash.bin \
	op/vec.bin \
	op/ver.bin \
	op/wantarray.bin \
	op/warn.bin \
	op/while_readdir.bin \
	op/write.bin \
	op/yadayada.bin

PERL=/usr/local/cpanel/3rdparty/perl/514/bin/perl
PROVE=/usr/local/cpanel/3rdparty/perl/514/bin/prove

TAINT_TESTS=$(TAINT_OK) $(TAINT_FAILURES)

TESTS=$(TESTS_OK) $(FAILURES)
REGULAR_TESTS=$(TESTS) $(TESTS:.bin=.subtest.bin)
ALL_TESTS=$(TAINT_TESTS) $(REGULAR_TESTS)

all: $(ALL_TESTS)

taint: $(TAINT_TESTS)

failures: $(TAINT_FAILURES) $(FAILURES)

$(TAINT_TESTS):
	$(PERL) -T -MO=-qq,C,-O2,-fno-fold,-o$(@:.bin=.c) $(@:.bin=.t)
	$(PERL) ../../script/cc_harness -q  $(@:.bin=.c) -o $@
	/bin/rm $(@:.bin=.c)

$(REGULAR_TESTS):
	$(PERL) -MO=-qq,C,-O2,-fno-fold,-o$(@:.bin=.c) $(@:.bin=.t)
	$(PERL) ../../script/cc_harness -q  $(@:.bin=.c) -o $@
	/bin/rm $(@:.bin=.c)

test: $(TESTS_OK) $(TAINT_OK)
	$(PROVE) -j 6 `find * -name \*.bin|grep -v .subtest.bin | sort`
	${MAKE} clean-cruft

bc:
	(cd ../.. && perl Makefile.PL installdirs=vendor && make install)

clean: clean-cruft
	/bin/rm -f $(ALL_TESTS) $(ALL_TESTS:.bin=.c)

clean-cruft:
	/bin/rm -f Io_argv*.tmp* tmp* utf*.pl a.out

depend:
	find * -name \*.t| sort| perl -ne 'chomp; s/\.t$$//; print "$$_.bin: $$_.t test.pl\n"' > depend.inc

-include depend.inc
